### ISSUE TITLE
IE 11 and Edge issues

### ISSUE THREAD

**Issue by nawalnew** [avidofood/vue-responsive-video-background-player#1]
Hello,

I have a urgent Problem.

The Video is not even Playing on all IE Browsers!

Is there a workaround for that? 

Thank you.

**Comment by nawalnew** [comment]
I found the Bug,

its "object-fit" 

But to get it to work,I need to add: "data-object-fit="cover"". to the video element somehow. 

Any Idea? Than it should work

**Comment by pmochine** [comment]
@nawalnew Oh sorry, I didn't get any mails and just saw the issue. I will try and have a look.

**Comment by pmochine** [comment]
Weird. I tested it here and it works: https://www.browserling.com/browse/win/7/ie/11/https%3A%2F%2Favidofood.github.io%2Fvue-responsive-video-background-player%2Fahttps%3A%2F%2Favidofood.github.io%2Fvue-responsive-video-background-player%2F

It should be easy to fix, however, I'm still not sure what I should do. You want to add `data-object-fit="cover"`, but I'm actually not sure why "data". I set object-fit with css? I guess it comes from this? https://github.com/constancecchen/object-fit-polyfill

**Comment by pmochine** [comment]
@nawalnew I need your help, I can't fix it because I don't have IE or Edge...

Could you have alook at : https://pmochine.github.io/delete-me-soon/

What's wrong there?

**Comment by nawalnew** [comment]
Hey @pmochine,

im Sorry fir the late reply. 

Your code works beautiful. 
i had just a stupid problem ( have it still )
--> If I try to view a Website in IE on my Virtual Machine ( Parallels ), than it isnt showed. But thats a Problem with Parallels! 

So the first Problem that the Video isnt showed is solved by doing the tzests on a real Windows Machine. 


To the Second problem:
Polyfills :) 

Ive fixed it with https://github.com/constancecchen/object-fit-polyfill
and your script works like a charm. 
Ive Implemented data-object-fit vie VueJS on the Compinent. and it works everithing fine now. 

im so sorry for your time with Troubleshooting. 

Thank you for your awesome help and your awesome Vue Component. it solves a lot of Problems and works nice!

**Comment by pmochine** [comment]
@nawalnew Ok as I understood it correctly, you have fixed it by adding object-fit-polyfill manually right? So I don't have to change the code?

Thank you for your kind words! I'll close the issue then, ok?
