### ISSUE TITLE
How to bind source?

### ISSUE THREAD

**Issue by baermathias** [avidofood/vue-responsive-video-background-player#15]
Whats the right way to bind the source? In contrast to the description within the readme file, only 3. works for me.

1. src="@/static/video.mp4"
2. src="../../static/video.mp4"
3. :src="require('@/static/video.mp4')"

**Comment by pmochine** [comment]
@baermathias Hey :) Thanks for the issue. I have updated the readme file, so it is clearer. Read [here](https://github.com/avidofood/vue-responsive-video-background-player/issues/10#issuecomment-646960914) for more or move the assets to the public folder (see [here](https://cli.vuejs.org/guide/html-and-static-assets.html#static-assets-handling))
