### ISSUE TITLE
Video fading

### ISSUE THREAD

**Issue by coruscateor** [avidofood/vue-responsive-video-background-player#19]
Is there a way to stop videos fading in and out when loaded and unloaded?

I can't find any options for disabling it in the readme and I can only find a transition element with the name attribute assigned "fade" and what appears to be some related styles in VideoPlayer.vue in the code.

**Comment by coruscateor** [comment]
Putting this:

```
.fade-enter-active{
  
  transition: none !important;

}

.fade-leave-active{

  transition: none !important;

}
```

in a non-scoped style in a parent component of the video-background (layout in my case) successfully prevents the fade effects from happening when the video is loaded and unloaded.

It would be more convenient of there was some option/attribute that would do this though.

**Comment by pmochine** [comment]
Sorry for responding now. I'm just so busy 🙈 It's an easy addition that I'm going to add. Thanks (not sure when I have time though, shouldn't be that long :D)

**Comment by coruscateor** [comment]
Thanks! I have no immediate need for this feature at the moment, so there's no need to hurry etc :)

**Comment by pmochine** [comment]
@coruscateor I have added this feature for version @1.2.1 and @2.1.1 
Thank you again :)

Props
...
- transition (default: fade)
You can add your own transition styles here. If you set it to empty string, it won't show any transitions.
