### ISSUE TITLE
Expose video controls and full screen

### ISSUE THREAD

**Issue by urbgimtam** [avidofood/vue-responsive-video-background-player#25]
Hello, and thank you for a great plugin. 

Is it possible to expose the regular ```<video>``` controls, or full screen?
What would be the best strategy to do so currently?

**Comment by pmochine** [comment]
@urbgimtam I tried to expose the controls, however, it's not possible for this package. For that, I would need a completely different structure or change the CSS on the fly... The overlay `<div>` blocks the controls.

Sorry!
