### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by Shawn-Armstrong** [avidofood/vue-responsive-video-background-player#38]
In the README.md under the header "Props values" the code blocks related to the Vue CLI notes are being improperly rendered in markdown leading to a syntax error that prompts a regex issue on the CLI.

Incorrect: `:src="require(`@/assets/demo.mp4`)"`

Correct: ``:src="require(`@/assets/demo.mp4`)"``

Proper markdown syntax call for the code block to be delimited with double back ticks.

**Comment by pmochine** [comment]
Hmm how weird, never noticed it. Thanks
