### ISSUE TITLE
TypeError Cannot read property 'pause' of undefined

### ISSUE THREAD

**Issue by lastch** [avidofood/vue-responsive-video-background-player#4]
Thanks for this library.
I use this library to display some videos as user story on a website.
I get this error if I switch to different page quickly(maybe when the video is loading).
Please check the below screenshot.
![image](https://user-images.githubusercontent.com/35144713/75988009-e959e000-5ebe-11ea-83ef-253ac89a89d1.png)

Could you add simple validation before the `pause()` called?
If you are busy, I can add it.

Thanks

**Comment by pmochine** [comment]
Updated NPM to vue-responsive-video-background-player@1.0.7,

have a check if it works :)

**Comment by lastch** [comment]
Thank you, I will check it right now
