### ISSUE TITLE
PlaybackRate

### ISSUE THREAD

**Issue by andrelec1** [avidofood/vue-responsive-video-background-player#7]
Can you add something for config the playbackRate ?

Actualy i have to do : 
```
document.getElementsByTagName('video')[0].playbackRate = 0.6;
document.getElementsByTagName('video')[0].defaultPlaybackRate = 0.6;
```

( the fadout/fadint anynamation seem to reset the playbackRate at the default value , so i apply the value en the playbackrate and defaultplaybackrate )

**Comment by pmochine** [comment]
@andrelec1 Thank you :) I just published a version with playbackRate as a prop. thank you for your recommendation :)
